"""Application layer: use cases plus the port contracts the core owns."""

from .correlation import CorrelatedFinding, CorrelationEngine
from .dto import (
    AdminChangePasswordRequest,
    ApiKeyView,
    AssessmentSummary,
    AssessmentView,
    CancelAssessmentRequest,
    CancelAssessmentResponse,
    ChangePasswordRequest,
    CreateApiKeyRequest,
    CreateApiKeyResponse,
    CreateAssessmentRequest,
    CreateAssessmentResponse,
    DeleteAssessmentRequest,
    DeleteAssessmentResponse,
    FindingView,
    GenerateReportRequest,
    GenerateReportResponse,
    GetAssessmentRequest,
    ListApiKeysRequest,
    ListAssessmentsRequest,
    ListAssessmentsResponse,
    LoginRequest,
    LoginResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    RegisterUserRequest,
    RegisterUserResponse,
    RenderedReport,
    RevokeApiKeyRequest,
    RotateApiKeyRequest,
    RotateApiKeyResponse,
    SeverityCount,
    StartAssessmentRequest,
    StartAssessmentResponse,
    SubmitAssessmentRequest,
    SubmitAssessmentResponse,
    UserView,
    ValidateApiKeyRequest,
    ValidateApiKeyResponse,
)
from .enrichment import EnrichedFinding, FindingEnricher
from .errors import (
    ApplicationError,
    AssessmentNotFoundError,
    InputValidationError,
    ReportNotFoundError,
    ScannerConfigError,
    ScannerDuplicateError,
    ScannerPluginError,
    ScannerTimeoutError,
    ScannerUnavailableError,
    ScannerVersionError,
)
from .events import (
    EVENT_ASSESSMENT_CANCELLED,
    EVENT_ASSESSMENT_COMPLETED,
    EVENT_ASSESSMENT_CREATED,
    EVENT_ASSESSMENT_DELETED,
    EVENT_ASSESSMENT_FAILED,
    EVENT_ASSESSMENT_RUNNING,
    EVENT_REPORT_READY,
    AssessmentEvent,
)
from .job import JobId
from .jobs import (
    IllegalJobTransitionError,
    InMemoryJobService,
    JobNotFoundError,
    JobStatus,
    ScanJob,
    ScanJobResult,
    validate_transition,
)
from .normalization import FindingNormalizer, NormalizedFinding
from .use_cases.audit_dto import (
    AuditEventView,
    RecordAuditEventRequest,
    RecordAuditEventResponse,
    SearchAuditEventsRequest,
    SearchAuditEventsResponse,
)
from .use_cases.record_audit_event import RecordAuditEvent
from .use_cases.search_audit_events import SearchAuditEvents
from .ports import (
    AIPort,
    ApiKeyHasher,
    ApiKeyRepository,
    AssessmentRepository,
    AuditEventRepository,
    Asset,
    AssetRepositoryPort,
    AuditPublisher,
    EventPublisher,
    JobRepositoryPort,
    JobRunner,
    PasswordHasher,
    ReportGenerationResult,
    ReportGeneratorPort,
    ReportRepository,
    ReportServicePort,
    ScannerExecutor,
    ScannerPluginPort,
    ScannerPluginRegistry,
    ScannerPort,
    ScanRepositoryPort,
    ServiceAPI,
    TokenClaims,
    TokenExpiredError,
    TokenInvalidError,
    TokenService,
    UnitOfWork,
    UnitOfWorkFactory,
    UserRepository,
)
from .risk import RiskAssessment, RiskFactor, RiskScorer
from .service_api import UseCaseServiceAPI
from .services.persistent_job_service import PersistentJobService
from .submit_assessment import SubmitAssessment
from .unit_of_work import UnitOfWorkPort
from .use_cases.cancel_assessment import CancelAssessment
from .use_cases.create_api_key import ApiKeyError, CreateApiKey
from .use_cases.list_api_keys import ListApiKeys
from .use_cases.revoke_api_key import ApiKeyNotFoundError, ApiKeyUnauthorizedError, RevokeApiKey
from .use_cases.rotate_api_key import RotateApiKey
from .use_cases.validate_api_key import ValidateApiKey
from .use_cases.change_password import ChangePassword, PasswordChangeError
from .use_cases.create_assessment import CreateAssessment
from .use_cases.delete_assessment import DeleteAssessment
from .use_cases.generate_report import GenerateReport
from .use_cases.get_assessment import GetAssessment
from .use_cases.list_assessments import ListAssessments
from .use_cases.login import AuthenticationError, Login
from .use_cases.refresh_token import RefreshToken, TokenRefreshError
from .use_cases.register_user import RegisterUser, RegistrationError
from .use_cases.start_assessment import StartAssessment

__all__ = [
    "EVENT_ASSESSMENT_CANCELLED",
    "EVENT_ASSESSMENT_COMPLETED",
    "EVENT_ASSESSMENT_CREATED",
    "EVENT_ASSESSMENT_DELETED",
    "EVENT_ASSESSMENT_FAILED",
    "EVENT_ASSESSMENT_RUNNING",
    "EVENT_REPORT_READY",
    "AIPort",
    "AdminChangePasswordRequest",
    "ApiKeyError",
    "ApiKeyHasher",
    "ApiKeyNotFoundError",
    "ApiKeyRepository",
    "ApiKeyUnauthorizedError",
    "ApiKeyView",
    "ApplicationError",
    "AssessmentEvent",
    "AssessmentNotFoundError",
    "AssessmentRepository",
    "AssessmentSummary",
    "AssessmentView",
    "Asset",
    "AssetRepositoryPort",
    "AuditEventRepository",
    "AuditEventView",
    "AuditPublisher",
    "AuthenticationError",
    "CancelAssessment",
    "CancelAssessmentRequest",
    "CancelAssessmentResponse",
    "ChangePassword",
    "ChangePasswordRequest",
    "CorrelatedFinding",
    "CorrelationEngine",
    "CreateApiKey",
    "CreateApiKeyRequest",
    "CreateApiKeyResponse",
    "CreateAssessment",
    "CreateAssessmentRequest",
    "CreateAssessmentResponse",
    "DeleteAssessment",
    "DeleteAssessmentRequest",
    "DeleteAssessmentResponse",
    "EnrichedFinding",
    "EventPublisher",
    "FindingEnricher",
    "FindingNormalizer",
    "FindingView",
    "GenerateReport",
    "GenerateReportRequest",
    "GenerateReportResponse",
    "GetAssessment",
    "GetAssessmentRequest",
    "IllegalJobTransitionError",
    "InMemoryJobService",
    "InputValidationError",
    "JobNotFoundError",
    "JobRepositoryPort",
    "JobRunner",
    "JobServicePort",
    "JobStatus",
    "ListApiKeys",
    "ListApiKeysRequest",
    "ListAssessments",
    "ListAssessmentsRequest",
    "ListAssessmentsResponse",
    "Login",
    "LoginRequest",
    "LoginResponse",
    "NormalizedFinding",
    "PasswordChangeError",
    "PasswordHasher",
    "PersistentJobService",
    "RefreshToken",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "RegisterUser",
    "RegisterUserRequest",
    "RegisterUserResponse",
    "RegistrationError",
    "RenderedReport",
    "ReportGenerationResult",
    "ReportGeneratorPort",
    "ReportNotFoundError",
    "ReportRepository",
    "ReportServicePort",
    "RevokeApiKey",
    "RevokeApiKeyRequest",
    "RiskAssessment",
    "RiskFactor",
    "RiskScorer",
    "RotateApiKey",
    "RotateApiKeyRequest",
    "RotateApiKeyResponse",
    "ScanJob",
    "ScanJobResult",
    "ScanRepositoryPort",
    "ScannerConfigError",
    "ScannerDuplicateError",
    "ScannerExecutor",
    "ScannerPluginError",
    "ScannerPluginPort",
    "ScannerPluginRegistry",
    "ScannerPort",
    "ScannerTimeoutError",
    "ScannerUnavailableError",
    "ScannerVersionError",
    "ServiceAPI",
    "SeverityCount",
    "StartAssessment",
    "StartAssessmentRequest",
    "StartAssessmentResponse",
    "SubmitAssessment",
    "SubmitAssessmentRequest",
    "SubmitAssessmentResponse",
    "TokenClaims",
    "TokenExpiredError",
    "TokenInvalidError",
    "TokenRefreshError",
    "TokenService",
    "UnitOfWork",
    "UnitOfWorkFactory",
    "UnitOfWorkPort",
    "UseCaseServiceAPI",
    "UserRepository",
    "UserView",
    "ValidateApiKey",
    "ValidateApiKeyRequest",
    "ValidateApiKeyResponse",
    "RecordAuditEvent",
    "RecordAuditEventRequest",
    "RecordAuditEventResponse",
    "SearchAuditEvents",
    "SearchAuditEventsRequest",
    "SearchAuditEventsResponse",
]
