"""no changes

Revision ID: 65bbc3c8cf23
Revises: 6f5df984fec8
Create Date: 2026-07-26 19:12:29.799973
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op
import sqlalchemy as sa


if TYPE_CHECKING:
    from alembic.runtime.revision import MigratorCollection


# revision identifiers, used by Alembic.
revision: str = "65bbc3c8cf23"
down_revision: str | None = "6f5df984fec8"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
