"""no changes

Revision ID: bc61babc6ca6
Revises: 50f943415a33
Create Date: 2026-07-23 18:09:53.653389
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'bc61babc6ca6'
down_revision: str | None = '50f943415a33'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
