"""add authorization_grants table and assessments.authorization_id (Phase 4 scope enforcement)

Revision ID: 289b5978e448
Revises: 9601803f77a8
Create Date: 2026-09-19 20:19:38.919240
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "289b5978e448"
down_revision: str | None = "9601803f77a8"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authorization_grants",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("authorized_by", sa.String(), nullable=False),
        sa.Column("authorizing_organization", sa.String(), nullable=False),
        sa.Column("target_specification_type", sa.String(), nullable=False),
        sa.Column("target_specification_value", sa.String(), nullable=False),
        sa.Column("valid_from", sa.String(), nullable=False),
        sa.Column("valid_until", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("revoked_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_authorization_grants_valid_from"), "authorization_grants", ["valid_from"], unique=False)
    op.create_index(op.f("ix_authorization_grants_valid_until"), "authorization_grants", ["valid_until"], unique=False)
    op.add_column("assessments", sa.Column("authorization_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assessments", "authorization_id")
    op.drop_index(op.f("ix_authorization_grants_valid_until"), table_name="authorization_grants")
    op.drop_index(op.f("ix_authorization_grants_valid_from"), table_name="authorization_grants")
    op.drop_table("authorization_grants")
    # ### end Alembic commands ###
