"""no changes

Revision ID: 709f42e3746f
Revises: 72ac8c3488e6
Create Date: 2026-07-20 23:08:47.604535
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "709f42e3746f"
down_revision: str | None = "72ac8c3488e6"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
