"""no changes

Revision ID: 28e2ef6aeff5
Revises: fef1c422d481
Create Date: 2026-07-19 01:40:10.724776
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '28e2ef6aeff5'
down_revision: str | None = 'fef1c422d481'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
