"""no changes

Revision ID: d4cbf257fd21
Revises: 2d9f6eea0a99
Create Date: 2026-07-23 18:22:54.185634
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "d4cbf257fd21"
down_revision: str | None = "2d9f6eea0a99"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
