"""no changes

Revision ID: d0c9d7fc8422
Revises: 4183cec2619a
Create Date: 2026-07-21 02:18:25.485233
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "d0c9d7fc8422"
down_revision: str | None = "4183cec2619a"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
