"""no changes

Revision ID: 06b5be1d5a21
Revises: 3ac57522d6ac
Create Date: 2026-07-19 15:24:09.831212
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '06b5be1d5a21'
down_revision: str | None = '3ac57522d6ac'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
