"""no changes

Revision ID: b47cdcccb9b5
Revises: 551e153a04ad
Create Date: 2026-07-19 01:30:53.868204
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'b47cdcccb9b5'
down_revision: str | None = '551e153a04ad'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
