"""no changes

Revision ID: 454589ae2dc1
Revises: ce2bc5c2b228
Create Date: 2026-07-21 16:04:01.087748
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "454589ae2dc1"
down_revision: str | None = "ce2bc5c2b228"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
