"""no changes

Revision ID: c9d0cc87bd07
Revises: c32f8be5dea8
Create Date: 2026-07-19 17:38:28.602763
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'c9d0cc87bd07'
down_revision: str | None = 'c32f8be5dea8'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
