"""no changes

Revision ID: 881f9ca0012c
Revises: 74c5c59d7e1f
Create Date: 2026-07-21 19:33:57.292337
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "881f9ca0012c"
down_revision: str | None = "74c5c59d7e1f"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
