"""no changes

Revision ID: 0d0b2458179a
Revises: fe98ad0ff862
Create Date: 2026-07-21 02:12:41.439927
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "0d0b2458179a"
down_revision: str | None = "fe98ad0ff862"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
