"""no changes

Revision ID: a803fc293d3a
Revises: f6e5d4c3b2a1
Create Date: 2026-07-28 16:50:39.959434
"""

from __future__ import annotations

from typing import TYPE_CHECKING



if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'a803fc293d3a'
down_revision: str | None = 'f6e5d4c3b2a1'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
