"""no changes

Revision ID: ce2bc5c2b228
Revises: eb33fbec64c2
Create Date: 2026-07-21 16:01:26.011364
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'ce2bc5c2b228'
down_revision: str | None = 'eb33fbec64c2'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
