"""no changes

Revision ID: 2d9f6eea0a99
Revises: a2beb2e44b78
Create Date: 2026-07-23 18:18:54.689133
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '2d9f6eea0a99'
down_revision: str | None = 'a2beb2e44b78'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
