"""no changes

Revision ID: 18bd841def00
Revises: 5dbfbd090eb0
Create Date: 2026-07-21 02:05:30.170711
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "18bd841def00"
down_revision: str | None = "5dbfbd090eb0"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
