"""no changes

Revision ID: 59c948f56c87
Revises: c1d7cf292974
Create Date: 2026-07-19 12:38:01.840785
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '59c948f56c87'
down_revision: str | None = 'c1d7cf292974'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
