"""no changes

Revision ID: 4ec4cf792d45
Revises: 6bea3093e601
Create Date: 2026-07-18 19:04:03.253300
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '4ec4cf792d45'
down_revision: str | None = '6bea3093e601'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
