"""no changes

Revision ID: 9b78c1d48a17
Revises: ce7147fe34cb
Create Date: 2026-07-19 12:40:31.332464
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '9b78c1d48a17'
down_revision: str | None = 'ce7147fe34cb'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
