"""no changes

Revision ID: 2dec9c19bba0
Revises: cefdaa20133d
Create Date: 2026-07-21 16:08:37.484328
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "2dec9c19bba0"
down_revision: str | None = "cefdaa20133d"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
