"""no changes

Revision ID: 53ae86c3ba9c
Revises: c97f2c7538b0
Create Date: 2026-07-23 00:28:10.487949
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '53ae86c3ba9c'
down_revision: str | None = 'c97f2c7538b0'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
