"""no changes

Revision ID: a245ff1963f0
Revises: 2ccd381e2853
Create Date: 2026-07-21 13:24:55.612667
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'a245ff1963f0'
down_revision: str | None = '2ccd381e2853'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
