"""no changes

Revision ID: 385412e253cd
Revises: 4c412c4aa7fa
Create Date: 2026-07-19 17:11:39.039799
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '385412e253cd'
down_revision: str | None = '4c412c4aa7fa'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
