"""no changes

Revision ID: f1dbc74507fd
Revises: 4f5767a28ae3
Create Date: 2026-07-23 00:36:17.943140
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'f1dbc74507fd'
down_revision: str | None = '4f5767a28ae3'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
