"""no changes

Revision ID: 0040363a7e7a
Revises: 2695b66ce6da
Create Date: 2026-07-18 21:02:21.997566
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '0040363a7e7a'
down_revision: str | None = '2695b66ce6da'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
