"""no changes

Revision ID: 60c7961a3859
Revises: 1bc157b2c11f
Create Date: 2026-07-21 13:38:36.225245
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '60c7961a3859'
down_revision: str | None = '1bc157b2c11f'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
