"""no changes

Revision ID: 967cf42a22de
Revises: 06b5be1d5a21
Create Date: 2026-07-19 15:42:00.716142
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '967cf42a22de'
down_revision: str | None = '06b5be1d5a21'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
