"""no changes

Revision ID: ba9fa68f4d9c
Revises: a795e00d0a5b
Create Date: 2026-07-19 19:38:13.964739
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'ba9fa68f4d9c'
down_revision: str | None = 'a795e00d0a5b'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
