"""no changes

Revision ID: 23facf2b75e5
Revises: d4db9fffb784
Create Date: 2026-07-19 16:55:02.126192
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '23facf2b75e5'
down_revision: str | None = 'd4db9fffb784'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
