"""no changes

Revision ID: 4a789fe2fed1
Revises: a245ff1963f0
Create Date: 2026-07-21 13:27:41.399336
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '4a789fe2fed1'
down_revision: str | None = 'a245ff1963f0'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
