"""no changes

Revision ID: 8cb8780e6958
Revises: 80b5fdbb6720
Create Date: 2026-07-19 01:45:46.959321
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '8cb8780e6958'
down_revision: str | None = '80b5fdbb6720'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
