"""no changes

Revision ID: 8cc90905998a
Revises: 6fbfb4fa0636
Create Date: 2026-07-19 20:22:57.652662
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '8cc90905998a'
down_revision: str | None = '6fbfb4fa0636'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
