"""no changes

Revision ID: 3ac57522d6ac
Revises: 93fef2e80cf6
Create Date: 2026-07-19 15:23:06.103877
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '3ac57522d6ac'
down_revision: str | None = '93fef2e80cf6'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
