"""no changes

Revision ID: de6ac0b9cd28
Revises: 5460513e3e79
Create Date: 2026-07-19 20:41:49.348608
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'de6ac0b9cd28'
down_revision: str | None = '5460513e3e79'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
