"""no changes

Revision ID: 67a90fd4df55
Revises: c88c03fce4c7
Create Date: 2026-07-19 15:15:36.096045
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '67a90fd4df55'
down_revision: str | None = 'c88c03fce4c7'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
