"""no changes

Revision ID: 5315bb9066f1
Revises: dc8702cefe14
Create Date: 2026-07-28 16:55:42.024452
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '5315bb9066f1'
down_revision: str | None = 'dc8702cefe14'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
