"""no changes

Revision ID: 4f5767a28ae3
Revises: 2ad76fdd5e96
Create Date: 2026-07-23 00:34:20.575281
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "4f5767a28ae3"
down_revision: str | None = "2ad76fdd5e96"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
