"""no changes

Revision ID: 070fde8c6234
Revises: 58b72c75b864
Create Date: 2026-07-21 01:46:16.547669
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "070fde8c6234"
down_revision: str | None = "58b72c75b864"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
