"""no changes

Revision ID: ce7147fe34cb
Revises: 59c948f56c87
Create Date: 2026-07-19 12:39:09.022455
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'ce7147fe34cb'
down_revision: str | None = '59c948f56c87'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
