"""no changes

Revision ID: be540a7c71cd
Revises: 2dec9c19bba0
Create Date: 2026-07-21 16:11:11.535342
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "be540a7c71cd"
down_revision: str | None = "2dec9c19bba0"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
