"""no changes

Revision ID: de8bdbbd0d38
Revises: a0db8a735709
Create Date: 2026-07-19 12:50:30.784164
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'de8bdbbd0d38'
down_revision: str | None = 'a0db8a735709'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
