"""no changes

Revision ID: 1428b7fc0eb1
Revises: ef79033a2da8
Create Date: 2026-07-20 00:53:11.475494
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op
import sqlalchemy as sa


if TYPE_CHECKING:
    from alembic.runtime.revision import MigratorCollection


# revision identifiers, used by Alembic.
revision: str = '1428b7fc0eb1'
down_revision: str | None = 'ef79033a2da8'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
