"""no changes

Revision ID: 8a7d42178500
Revises: db6d9f97588d
Create Date: 2026-07-21 13:46:56.334913
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '8a7d42178500'
down_revision: str | None = 'db6d9f97588d'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
