"""no changes

Revision ID: fdb5f777384d
Revises: fbd24a3476b2
Create Date: 2026-07-21 20:57:16.112128
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "fdb5f777384d"
down_revision: str | None = "fbd24a3476b2"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
