"""no changes

Revision ID: c1de3bfc44e3
Revises: 5bcea4cd2654
Create Date: 2026-07-19 19:28:25.759874
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'c1de3bfc44e3'
down_revision: str | None = '5bcea4cd2654'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
