"""no changes

Revision ID: 11a2fdf39a09
Revises: df4b39b146f9
Create Date: 2026-07-19 20:45:53.234366
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '11a2fdf39a09'
down_revision: str | None = 'df4b39b146f9'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
