"""no changes

Revision ID: fde8bf6ffc36
Revises: 8a5a54d33169
Create Date: 2026-07-19 16:51:30.823112
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'fde8bf6ffc36'
down_revision: str | None = '8a5a54d33169'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
