"""no changes

Revision ID: 155abce6b6ea
Revises: ba9fa68f4d9c
Create Date: 2026-07-19 19:39:37.761967
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '155abce6b6ea'
down_revision: str | None = 'ba9fa68f4d9c'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
