"""no changes

Revision ID: 22b0cef71b01
Revises: 9800c9642fd0
Create Date: 2026-07-15 16:23:48.420043
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op
import sqlalchemy as sa


if TYPE_CHECKING:
    from alembic.runtime.revision import MigratorCollection


# revision identifiers, used by Alembic.
revision: str = '22b0cef71b01'
down_revision: str | None = '9800c9642fd0'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
