"""no changes

Revision ID: 5542ea1b2496
Revises: 8cb8780e6958
Create Date: 2026-07-19 01:47:58.845824
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '5542ea1b2496'
down_revision: str | None = '8cb8780e6958'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
