"""no changes

Revision ID: a97dd839352f
Revises: a8b291cabc58
Create Date: 2026-07-19 20:33:54.214528
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'a97dd839352f'
down_revision: str | None = 'a8b291cabc58'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
