"""no changes

Revision ID: 62bec3409f26
Revises: 9b78c1d48a17
Create Date: 2026-07-19 12:46:35.770664
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '62bec3409f26'
down_revision: str | None = '9b78c1d48a17'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
