"""no changes

Revision ID: d4db9fffb784
Revises: fde8bf6ffc36
Create Date: 2026-07-19 16:53:21.803265
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'd4db9fffb784'
down_revision: str | None = 'fde8bf6ffc36'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
