"""no changes

Revision ID: 2959d56f5e00
Revises: 3d277c707dfc
Create Date: 2026-07-21 21:31:02.255524
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "2959d56f5e00"
down_revision: str | None = "3d277c707dfc"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
