"""no changes

Revision ID: f4cf3cf2f913
Revises: 35083f03929b
Create Date: 2026-07-21 16:18:03.733358
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'f4cf3cf2f913'
down_revision: str | None = '35083f03929b'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
