"""no changes

Revision ID: a8b291cabc58
Revises: 8cc90905998a
Create Date: 2026-07-19 20:24:45.002592
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op
import sqlalchemy as sa


if TYPE_CHECKING:
    from alembic.runtime.revision import MigratorCollection


# revision identifiers, used by Alembic.
revision: str = 'a8b291cabc58'
down_revision: str | None = '8cc90905998a'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
