"""no changes

Revision ID: c51a92c2ced9
Revises: 424f736bed43
Create Date: 2026-07-13 17:25:48.837152
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op
import sqlalchemy as sa


if TYPE_CHECKING:
    from alembic.runtime.revision import MigratorCollection


# revision identifiers, used by Alembic.
revision: str = 'c51a92c2ced9'
down_revision: str | None = '424f736bed43'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
