"""no changes

Revision ID: df4b39b146f9
Revises: de6ac0b9cd28
Create Date: 2026-07-19 20:43:45.449818
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'df4b39b146f9'
down_revision: str | None = 'de6ac0b9cd28'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
