"""no changes

Revision ID: 53793db97f9f
Revises: d0c9d7fc8422
Create Date: 2026-07-21 02:20:18.542705
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '53793db97f9f'
down_revision: str | None = 'd0c9d7fc8422'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
