"""no changes

Revision ID: 74c5c59d7e1f
Revises: 2f9931879b20
Create Date: 2026-07-21 19:31:17.047405
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = "74c5c59d7e1f"
down_revision: str | None = "2f9931879b20"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
