"""no changes

Revision ID: 216cecfb8ded
Revises: b7f1521054aa
Create Date: 2026-07-19 18:48:08.513158
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = '216cecfb8ded'
down_revision: str | None = 'b7f1521054aa'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
