"""no changes

Revision ID: a2beb2e44b78
Revises: bc61babc6ca6
Create Date: 2026-07-23 18:16:30.932048
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'a2beb2e44b78'
down_revision: str | None = 'bc61babc6ca6'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
