"""no changes

Revision ID: ef63819946b5
Revises: 7f1c0fcf8687
Create Date: 2026-07-18 19:14:33.084487
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# revision identifiers, used by Alembic.
revision: str = 'ef63819946b5'
down_revision: str | None = '7f1c0fcf8687'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
