"""OpenAPI specification configuration.

Polishes the OpenAPI document with organized tags, descriptions, and
security schemes. The spec is generated by FastAPI; this module customizes
the metadata.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from fastapi import FastAPI

if TYPE_CHECKING:
    from kingsec.infrastructure.config.models import AppSettings

# OpenAPI tag descriptions for endpoint grouping.
TAGS = [
    {
        "name": "health",
        "description": "Health check endpoints for monitoring and load balancers.",
    },
    {
        "name": "auth",
        "description": "Authentication and user management. Register, login, and manage tokens.",
    },
    {
        "name": "assessments",
        "description": "Assessment lifecycle: create, start, query, cancel, and delete assessments.",
    },
    {
        "name": "reports",
        "description": "Report generation and retrieval for completed assessments.",
    },
    {
        "name": "events",
        "description": "Server-Sent Events for real-time assessment progress streaming.",
    },
    {
        "name": "audit",
        "description": "Security audit trail. Immutable record of all actions. ADMIN role required.",
    },
]


def configure_openapi(app: FastAPI, settings: AppSettings) -> None:
    """Configure the OpenAPI specification for the application."""
    app.title = "KingSec API"
    app.version = settings.version
    app.description = (
        "Local-first, AI-augmented Attack Surface & Vulnerability Management API.\n\n"
        "## Authentication\n\n"
        "All endpoints (except health and auth) require a JWT Bearer token.\n"
        "Obtain tokens via `/api/v1/auth/login`.\n\n"
        "## Rate Limiting\n\n"
        "API endpoints: 120 requests/minute per IP.\n"
        "Auth endpoints: 20 requests/minute per IP.\n\n"
        "## Audit Trail\n\n"
        "All mutations are recorded in an immutable audit trail.\n"
        "Query via `GET /api/v1/audit` (ADMIN role required).\n\n"
        "## Versioning\n\n"
        "API is versioned via URL prefix: `/api/v1/...`.\n"
    )

    openapi_schema = app.openapi()
    if openapi_schema:
        openapi_schema["tags"] = TAGS
        openapi_schema["components"] = openapi_schema.get("components", {})
        openapi_schema["components"]["securitySchemes"] = {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "JWT access token from `/api/v1/auth/login`",
            }
        }
