"""KingSec domain layer -- pure business model, standard-library only.

This package has NO outward dependencies: no infrastructure, no application, no
shared kernel, no third-party libraries. Everything below is expressed in plain
Python so the core business rules can be understood and tested in isolation.
"""

from __future__ import annotations

from .api_key import ApiKey, ApiKeyScope, ApiKeyStatus
from .assessment import Assessment, ScannerRunSummary
from .asset import (
    Asset,
    AssetCriticality,
    AssetHistoryEntry,
    AssetRelationship,
    AssetService,
    AssetTag,
    AssetType,
    TechnologyFingerprint,
)
from .audit import AuditAction, AuditEntry
from .audit_event import AuditEvent, AuditEventId, AuditOutcome, AuditSeverity
from .authorization import Authorization
from .backup import (
    BackupId,
    BackupMetadata,
    BackupSnapshot,
    BackupStatus,
    BackupType,
    RestoreOperation,
    RetentionPolicy,
)
from .enums import AssessmentStatus, FindingStatus, Role, ScannerRunState, Severity
from .errors import DomainError, IllegalStateTransition, InvariantViolation
from .evidence import Evidence, Recommendation
from .finding import Finding
from .identifiers import (
    AssessmentId,
    AssetId,
    ComplianceFrameworkId,
    FindingId,
    MappingId,
    ReportId,
    ScanId,
    ScheduleId,
)
from .integration import (
    DeliveryRecord,
    DeliveryStatus,
    IntegrationConfig,
    IntegrationStatus,
    IntegrationType,
    SIEMBatchResult,
    TicketReference,
    WebhookEventType,
)
from .mfa import MfaRecoveryCode, MfaSecret, MfaStatus, RecoveryCodeStatus
from .organization import (
    OrgActivityEvent,
    Organization,
    OrganizationId,
    OrganizationMembership,
    OrgEventType,
    OrgRole,
    Team,
    TeamId,
    TeamMembership,
)
from .pipeline import (
    PIPELINE_ORDER,
    PipelineExecution,
    PipelineId,
    PipelineResult,
    PipelineStage,
    PipelineState,
)
from .rate_limit import (
    AccountLockout,
    LockoutPolicy,
    RateLimitBucket,
    RateLimitDecision,
    RateLimitExceeded,
    RateLimitGroup,
    RateLimitKeyType,
    RateLimitPolicy,
)
from .report import FindingSummary, HistoryPoint, Report, Verdict
from .scanner import (
    OutputFormat,
    PluginAvailability,
    PluginConfig,
    ScanCategory,
    ScannerCapability,
    ScannerId,
    ScannerPluginMetadata,
    ScannerRequirement,
    ScannerResult,
    provided_requirements,
)
from .schedule import (
    RetryPolicy,
    RetryStrategy,
    ScanSchedule,
    ScheduleStatus,
    ScheduleType,
)
from .secret import SecretId, SecretMetadata, SecretType
from .session import (
    DeviceInfo,
    Session,
    SessionId,
    SessionStatus,
    SessionType,
)
from .system_health import (
    DependencyHealth,
    HealthCheck,
    HealthStatus,
    LivenessReport,
    ReadinessReport,
    ResourceUsage,
    ServiceStatus,
    StartupCheck,
    SystemMetrics,
)
from .target import Target, TargetType
from .user import (
    InvalidCredentialsError,
    PasswordValidationError,
    User,
    UserDisabledError,
    UserError,
    UserNotFoundError,
)

__all__ = [
    "PIPELINE_ORDER",
    "AccountLockout",
    "ApiKey",
    "ApiKeyScope",
    "ApiKeyStatus",
    "Assessment",
    "AssessmentId",
    "AssessmentStatus",
    "Asset",
    "AssetCriticality",
    "AssetHistoryEntry",
    "AssetId",
    "AssetRelationship",
    "AssetService",
    "AssetTag",
    "AssetType",
    "AuditAction",
    "AuditEntry",
    "AuditEvent",
    "AuditEventId",
    "AuditOutcome",
    "AuditSeverity",
    "Authorization",
    "BackupId",
    "BackupMetadata",
    "BackupSnapshot",
    "BackupStatus",
    "BackupType",
    "ComplianceFrameworkId",
    "DeliveryRecord",
    "DeliveryStatus",
    "DependencyHealth",
    "DeviceInfo",
    "DomainError",
    "Evidence",
    "Finding",
    "FindingId",
    "FindingStatus",
    "FindingSummary",
    "HealthCheck",
    "HealthStatus",
    "HistoryPoint",
    "IllegalStateTransition",
    "IntegrationConfig",
    "IntegrationStatus",
    "IntegrationType",
    "InvalidCredentialsError",
    "InvariantViolation",
    "LivenessReport",
    "LockoutPolicy",
    "MappingId",
    "MfaRecoveryCode",
    "MfaSecret",
    "MfaStatus",
    "OrgActivityEvent",
    "OrgEventType",
    "OrgRole",
    "Organization",
    "OrganizationId",
    "OrganizationMembership",
    "OutputFormat",
    "PasswordValidationError",
    "PipelineExecution",
    "PipelineId",
    "PipelineResult",
    "PipelineStage",
    "PipelineState",
    "PluginAvailability",
    "PluginConfig",
    "RateLimitBucket",
    "RateLimitDecision",
    "RateLimitExceeded",
    "RateLimitGroup",
    "RateLimitKeyType",
    "RateLimitPolicy",
    "ReadinessReport",
    "Recommendation",
    "RecoveryCodeStatus",
    "Report",
    "ReportId",
    "ResourceUsage",
    "RestoreOperation",
    "RetentionPolicy",
    "RetryPolicy",
    "RetryStrategy",
    "Role",
    "SIEMBatchResult",
    "ScanCategory",
    "ScanId",
    "ScanSchedule",
    "ScannerCapability",
    "ScannerId",
    "ScannerPluginMetadata",
    "ScannerRequirement",
    "ScannerResult",
    "ScannerRunState",
    "ScannerRunSummary",
    "ScheduleId",
    "ScheduleStatus",
    "ScheduleType",
    "SecretId",
    "SecretMetadata",
    "SecretType",
    "ServiceStatus",
    "Session",
    "SessionId",
    "SessionStatus",
    "SessionType",
    "Severity",
    "StartupCheck",
    "SystemMetrics",
    "Target",
    "TargetType",
    "Team",
    "TeamId",
    "TeamMembership",
    "TechnologyFingerprint",
    "TicketReference",
    "User",
    "UserDisabledError",
    "UserError",
    "UserNotFoundError",
    "Verdict",
    "WebhookEventType",
    "provided_requirements",
]
