#!/usr/bin/env bash
# KingSec source installer for Linux and macOS.
# Run from a repository checkout: ./scripts/install.sh
set -euo pipefail
umask 077

KINGSEC_REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KINGSEC_DATA_DIR="${KINGSEC_DATA_DIR:-${KINGSEC_REPO_DIR}/data}"
KINGSEC_DEV_MODE="${KINGSEC_DEV_MODE:-false}"
KINGSEC_ENV_FILE="${KINGSEC_REPO_DIR}/.env"
KINGSEC_VENV_DIR="${KINGSEC_REPO_DIR}/.venv"
KINGSEC_NPM_CACHE_DIR="${KINGSEC_REPO_DIR}/.npm-cache"

info() { printf '\033[0;34m>> %s\033[0m\n' "$1"; }
ok() { printf '\033[0;32m   [OK] %s\033[0m\n' "$1"; }
warn() { printf '\033[0;33m   [WARN] %s\033[0m\n' "$1"; }
fail() { printf '\033[0;31m   [FAIL] %s\033[0m\n' "$1" >&2; exit 1; }
has() { command -v "$1" >/dev/null 2>&1; }

run_kingsec() {
    (
        cd "$KINGSEC_REPO_DIR"
        # Migration-only overrides can otherwise send Alembic to a different
        # database than the server.  This installer deliberately manages one
        # SQLite data directory, supplied explicitly for every KingSec command.
        unset ALEMBIC_DATABASE_URL KINGSEC_STORAGE__DATABASE_URL
        KINGSEC_STORAGE__DATA_DIR="$KINGSEC_DATA_DIR" "$@"
    )
}

info "Checking required toolchain"
if has python3; then
    KINGSEC_PYTHON_BIN="$(command -v python3)"
elif has python; then
    KINGSEC_PYTHON_BIN="$(command -v python)"
else
    fail "Python is missing. Install CPython 3.11, 3.12, or 3.13 and rerun this script."
fi

if ! "$KINGSEC_PYTHON_BIN" -c 'import sys; raise SystemExit(0 if (3, 11) <= sys.version_info[:2] <= (3, 13) else 1)'; then
    fail "KingSec supports Python 3.11-3.13. Found: $($KINGSEC_PYTHON_BIN --version 2>&1)"
fi
ok "Found $($KINGSEC_PYTHON_BIN --version 2>&1)"

has node || fail "Node.js is missing. Install Node.js 20 or newer to build the browser UI."
has npm || fail "npm is missing. Install the npm version bundled with Node.js 20 or newer."
KINGSEC_NODE_MAJOR="$(node -p "process.versions.node.split('.')[0]")"
if [ "$KINGSEC_NODE_MAJOR" -lt 20 ]; then
    fail "Node.js 20 or newer is required. Found: $(node --version)"
fi
ok "Found Node.js $(node --version) and npm $(npm --version)"

info "Creating the isolated Python environment"
"$KINGSEC_PYTHON_BIN" -m venv "$KINGSEC_VENV_DIR"
KINGSEC_VENV_PYTHON="${KINGSEC_VENV_DIR}/bin/python"
"$KINGSEC_VENV_PYTHON" -m pip install --upgrade pip
ok "Virtual environment ready at $KINGSEC_VENV_DIR"

info "Building the browser UI"
mkdir -p "$KINGSEC_NPM_CACHE_DIR"
npm --cache "$KINGSEC_NPM_CACHE_DIR" --prefix "${KINGSEC_REPO_DIR}/frontend" ci
npm --cache "$KINGSEC_NPM_CACHE_DIR" --prefix "${KINGSEC_REPO_DIR}/frontend" run build
KINGSEC_STATIC_DIR="${KINGSEC_REPO_DIR}/src/kingsec/adapters/inbound/web/static"
rm -rf -- "$KINGSEC_STATIC_DIR"
mkdir -p "$KINGSEC_STATIC_DIR"
cp -R "${KINGSEC_REPO_DIR}/frontend/dist/." "$KINGSEC_STATIC_DIR/"
ok "Browser UI built for same-origin serving"

info "Installing KingSec into the checkout virtual environment"
if [ "$KINGSEC_DEV_MODE" = "true" ]; then
    (cd "$KINGSEC_REPO_DIR" && "$KINGSEC_VENV_PYTHON" -m pip install --only-binary=cffi,pydantic-core -e ".[dev]")
else
    (cd "$KINGSEC_REPO_DIR" && "$KINGSEC_VENV_PYTHON" -m pip install --only-binary=cffi,pydantic-core .)
fi
ok "KingSec installed"

KINGSEC_REPORT_FORMAT="html"
if "$KINGSEC_VENV_PYTHON" -c 'from weasyprint import HTML; HTML(string="<p>KingSec PDF preflight</p>").write_pdf()' >/dev/null 2>&1; then
    KINGSEC_REPORT_FORMAT="pdf"
    ok "PDF report rendering is available"
else
    warn "PDF native libraries are unavailable; defaulting reports to HTML (see docs/INSTALL.md)"
fi

info "Preparing local configuration"
mkdir -p "$KINGSEC_DATA_DIR"
KINGSEC_DATA_DIR="$(cd "$KINGSEC_DATA_DIR" && pwd -P)"
chmod 700 "$KINGSEC_DATA_DIR"
if [ ! -f "$KINGSEC_ENV_FILE" ]; then
    read -r KINGSEC_JWT_SECRET KINGSEC_API_PEPPER KINGSEC_ENCRYPTION_KEY < <(
        "$KINGSEC_PYTHON_BIN" -c 'import base64, secrets; print(secrets.token_urlsafe(48), secrets.token_urlsafe(48), base64.urlsafe_b64encode(secrets.token_bytes(32)).decode())'
    )
    KINGSEC_DATA_DIR_ENV="$("$KINGSEC_PYTHON_BIN" -c 'import json, sys; print(json.dumps(sys.argv[1]))' "$KINGSEC_DATA_DIR")"
    cat > "$KINGSEC_ENV_FILE" <<EOF
# Generated by scripts/install.sh. Keep this file private.
KINGSEC_APP__ENVIRONMENT=production
KINGSEC_LOGGING__LEVEL=INFO
KINGSEC_JWT__SECRET_KEY=$KINGSEC_JWT_SECRET
KINGSEC_SECRETS__API_KEY_PEPPER=$KINGSEC_API_PEPPER
KINGSEC_SECRETS__ENCRYPTION_KEY=$KINGSEC_ENCRYPTION_KEY
KINGSEC_SERVER__HOST=127.0.0.1
KINGSEC_SERVER__PORT=8765
KINGSEC_STORAGE__DATA_DIR=$KINGSEC_DATA_DIR_ENV
KINGSEC_REPORTING__REPORT_FORMAT=$KINGSEC_REPORT_FORMAT
EOF
    chmod 600 "$KINGSEC_ENV_FILE"
    ok "Created $KINGSEC_ENV_FILE with unique secrets"
else
    ok "Preserved existing $KINGSEC_ENV_FILE"
    warn "The installer and generated launcher explicitly use data directory $KINGSEC_DATA_DIR"
fi

info "Validating configuration and cryptographic secrets"
run_kingsec "$KINGSEC_VENV_PYTHON" -c 'from kingsec.bootstrap.container import Container; from kingsec.infrastructure.auth.provisioning import register_api_key_auth, register_auth; from kingsec.infrastructure.config import load_settings; from kingsec.infrastructure.secrets.provisioning import register_secrets; settings = load_settings(); container = Container(); register_auth(container, settings); register_api_key_auth(container, lambda: None, settings); register_secrets(container, settings, str(settings.storage.data_dir / "secrets.json"))'
ok "Configuration and cryptographic secrets are valid"

KINGSEC_DATABASE_PATH="${KINGSEC_DATA_DIR}/kingsec.db"
if [ -f "$KINGSEC_DATABASE_PATH" ]; then
    info "Creating a consistent SQLite snapshot before migration"
    KINGSEC_BACKUP_DIR="${KINGSEC_DATA_DIR}/backups"
    mkdir -p "$KINGSEC_BACKUP_DIR"
    KINGSEC_BACKUP_STAMP="$($KINGSEC_VENV_PYTHON -c 'from datetime import UTC, datetime; print(datetime.now(UTC).strftime("%Y%m%dT%H%M%S%fZ"))')"
    KINGSEC_BACKUP_PATH="${KINGSEC_BACKUP_DIR}/kingsec-pre-install-${KINGSEC_BACKUP_STAMP}.db"
    run_kingsec "$KINGSEC_VENV_PYTHON" -c 'import sqlite3, sys; source = sqlite3.connect(sys.argv[1]); destination = sqlite3.connect(sys.argv[2]); source.backup(destination); destination.close(); source.close()' "$KINGSEC_DATABASE_PATH" "$KINGSEC_BACKUP_PATH"
    chmod 600 "$KINGSEC_BACKUP_PATH"
    ok "Database snapshot saved to $KINGSEC_BACKUP_PATH"
fi

info "Applying database migrations"
run_kingsec "$KINGSEC_VENV_PYTHON" -m kingsec._migrate
ok "Database is ready"

info "Running the read-only scanner preflight"
if run_kingsec "$KINGSEC_VENV_PYTHON" -m kingsec doctor; then
    ok "All scanners in the default doctor profile are usable"
else
    warn "One or more scanners in the default doctor profile are unavailable; review the output above"
fi

{
    printf '%s\n' '#!/usr/bin/env bash' 'set -euo pipefail'
    printf 'cd %q\n' "$KINGSEC_REPO_DIR"
    printf '%s\n' 'unset ALEMBIC_DATABASE_URL KINGSEC_STORAGE__DATABASE_URL'
    printf 'KINGSEC_STORAGE__DATA_DIR=%q exec %q -m kingsec\n' "$KINGSEC_DATA_DIR" "$KINGSEC_VENV_PYTHON"
} > "${KINGSEC_DATA_DIR}/start.sh"
chmod 700 "${KINGSEC_DATA_DIR}/start.sh"

if [ -t 0 ]; then
    printf 'Create the first admin now? [y/N] '
    read -r KINGSEC_BOOTSTRAP_REPLY
    if [[ "$KINGSEC_BOOTSTRAP_REPLY" =~ ^[Yy]$ ]]; then
        printf 'Admin username: '
        read -r KINGSEC_ADMIN_USERNAME
        run_kingsec "$KINGSEC_VENV_PYTHON" -m kingsec._bootstrap --username "$KINGSEC_ADMIN_USERNAME"
    fi
fi

ok "Installation complete"
printf 'Start KingSec with: %s\n' "${KINGSEC_DATA_DIR}/start.sh"
printf 'Create/recover the admin later with: cd %q && KINGSEC_STORAGE__DATA_DIR=%q %q -m kingsec._bootstrap --username admin\n' \
    "$KINGSEC_REPO_DIR" "$KINGSEC_DATA_DIR" "$KINGSEC_VENV_PYTHON"
printf 'Then open: http://127.0.0.1:8765/\n'
