from __future__ import annotations

from kingsec.domain.compliance import ComplianceFramework, ControlId, FrameworkControl

FRAMEWORK_DEFINITIONS: dict[ComplianceFramework, tuple[FrameworkControl, ...]] = {}


def _control(
    framework: ComplianceFramework,
    ctrl_id: str,
    title: str,
    description: str,
    category: str = "",
) -> FrameworkControl:
    return FrameworkControl(
        framework=framework,
        control_id=ControlId(ctrl_id),
        title=title,
        description=description,
        category=category,
    )


C = ComplianceFramework

FRAMEWORK_DEFINITIONS[C.CIS_V8] = (
    _control(C.CIS_V8, "1.1", "Establish and maintain detailed enterprise asset inventory", "Maintain an accurate inventory of all enterprise assets", "Asset Management"),
    _control(C.CIS_V8, "1.2", "Track and manage software inventory", "Maintain a software inventory of all authorized software", "Asset Management"),
    _control(C.CIS_V8, "2.1", "Establish and maintain a software inventory", "Establish and maintain a software inventory across the enterprise", "Software Asset Management"),
    _control(C.CIS_V8, "3.1", "Configure data protection controls", "Establish and maintain data protection controls", "Data Protection"),
    _control(C.CIS_V8, "3.3", "Encrypt sensitive data in transit", "Encrypt sensitive data in transit over untrusted networks", "Data Protection"),
    _control(C.CIS_V8, "3.4", "Encrypt sensitive data at rest", "Encrypt sensitive data at rest on servers and endpoints", "Data Protection"),
    _control(C.CIS_V8, "4.1", "Establish and maintain a secure configuration process", "Establish and maintain a secure configuration process for enterprise assets", "Secure Configuration"),
    _control(C.CIS_V8, "4.4", "Implement and manage a firewall on servers", "Implement and manage a firewall on servers where supported", "Secure Configuration"),
    _control(C.CIS_V8, "4.7", "Manage default accounts on enterprise assets", "Manage default accounts on enterprise assets and software", "Secure Configuration"),
    _control(C.CIS_V8, "5.1", "Establish and maintain an inventory of accounts", "Establish and maintain an inventory of all accounts", "Account Management"),
    _control(C.CIS_V8, "5.2", "Use unique passwords", "Use unique passwords for all enterprise assets", "Account Management"),
    _control(C.CIS_V8, "5.4", "Restrict administrator privileges", "Restrict administrator privileges to dedicated administrator accounts", "Account Management"),
    _control(C.CIS_V8, "6.1", "Establish and maintain an access control process", "Establish and maintain an access control process for enterprise assets", "Access Control"),
    _control(C.CIS_V8, "6.3", "Require MFA for administrative access", "Require multi-factor authentication for administrative access", "Access Control"),
    _control(C.CIS_V8, "6.4", "Require MFA for remote network access", "Require MFA for all remote network access", "Access Control"),
    _control(C.CIS_V8, "7.1", "Establish and maintain a vulnerability management process", "Establish and maintain a vulnerability management process for enterprise assets", "Vulnerability Management"),
    _control(C.CIS_V8, "7.4", "Perform automated vulnerability scans", "Perform automated vulnerability scans of internal enterprise assets", "Vulnerability Management"),
    _control(C.CIS_V8, "7.6", "Conduct automated patch management", "Conduct automated patch management of enterprise assets", "Vulnerability Management"),
    _control(C.CIS_V8, "8.1", "Establish and maintain an audit log management process", "Establish and maintain an audit log management process", "Audit Log Management"),
    _control(C.CIS_V8, "8.2", "Collect audit logs", "Collect audit logs from enterprise assets", "Audit Log Management"),
    _control(C.CIS_V8, "8.3", "Ensure adequate audit log retention", "Ensure adequate audit log retention", "Audit Log Management"),
    _control(C.CIS_V8, "8.5", "Collect detailed audit logs", "Collect detailed audit logs for high-risk assets", "Audit Log Management"),
    _control(C.CIS_V8, "9.1", "Implement email and web browser protections", "Implement protections for email and web browsers", "Email and Web Protections"),
    _control(C.CIS_V8, "9.2", "Use DNS filtering services", "Use DNS filtering services to block access to malicious domains", "Email and Web Protections"),
    _control(C.CIS_V8, "10.1", "Establish and maintain a data recovery process", "Establish and maintain a data recovery process", "Data Recovery"),
    _control(C.CIS_V8, "10.2", "Perform automated backups", "Perform automated backups of enterprise assets", "Data Recovery"),
    _control(C.CIS_V8, "10.4", "Protect backup data", "Protect backup data with encryption and access controls", "Data Recovery"),
    _control(C.CIS_V8, "11.1", "Establish and maintain a network defense process", "Establish and maintain a network defense process", "Network Defenses"),
    _control(C.CIS_V8, "11.2", "Manage network filtering", "Manage network filtering and segmentation controls", "Network Defenses"),
    _control(C.CIS_V8, "12.1", "Establish and maintain a security awareness program", "Establish and maintain a security awareness program", "Security Awareness"),
    _control(C.CIS_V8, "12.2", "Train workforce on security awareness", "Train workforce members on security awareness principles", "Security Awareness"),
    _control(C.CIS_V8, "13.1", "Establish and maintain a data management process", "Establish and maintain a data management process", "Data Management"),
    _control(C.CIS_V8, "14.1", "Establish and maintain a security program", "Establish and maintain a security program for the enterprise", "Security Operations"),
    _control(C.CIS_V8, "14.2", "Establish and maintain a security incident response process", "Establish and maintain a security incident response process", "Security Operations"),
    _control(C.CIS_V8, "15.1", "Establish and maintain a service provider management program", "Establish and maintain a service provider management program", "Service Provider Management"),
    _control(C.CIS_V8, "16.1", "Establish and maintain a secure application development program", "Establish and maintain a secure application development program", "Application Security"),
    _control(C.CIS_V8, "16.3", "Perform code review", "Perform code review for application security changes", "Application Security"),
    _control(C.CIS_V8, "16.6", "Use web application firewalls", "Use web application firewalls to protect publicly facing applications", "Application Security"),
)

FRAMEWORK_DEFINITIONS[C.NIST_CSF_2] = (
    _control(C.NIST_CSF_2, "ID.AM-1", "Physical devices and systems are inventoried", "Physical devices and systems within the organization are inventoried", "Asset Management"),
    _control(C.NIST_CSF_2, "ID.AM-2", "Software platforms and applications are inventoried", "Software platforms and applications within the organization are inventoried", "Asset Management"),
    _control(C.NIST_CSF_2, "ID.AM-3", "Organizational communication and data flows are mapped", "Organizational communication and data flows are mapped", "Asset Management"),
    _control(C.NIST_CSF_2, "ID.AM-5", "Resources are prioritized based on classification", "Resources are prioritized based on their classification, criticality, and business value", "Asset Management"),
    _control(C.NIST_CSF_2, "ID.GV-1", "Organizational cybersecurity policy is established", "Organizational cybersecurity policy is established and communicated", "Governance"),
    _control(C.NIST_CSF_2, "ID.RA-1", "Asset vulnerabilities are identified and documented", "Asset vulnerabilities are identified and documented", "Risk Assessment"),
    _control(C.NIST_CSF_2, "ID.RA-2", "Threat intelligence is received", "Threat and vulnerability information is received from information sharing forums", "Risk Assessment"),
    _control(C.NIST_CSF_2, "ID.RA-3", "Threats are identified and documented", "Threats, both internal and external, are identified and documented", "Risk Assessment"),
    _control(C.NIST_CSF_2, "ID.RA-4", "Business impact is assessed", "Potential business impacts and likelihoods are identified", "Risk Assessment"),
    _control(C.NIST_CSF_2, "ID.RA-5", "Risk is assessed", "Threats, vulnerabilities, likelihoods, and impacts are used to determine risk", "Risk Assessment"),
    _control(C.NIST_CSF_2, "ID.RA-6", "Risk responses are identified", "Risk responses are identified and prioritized", "Risk Assessment"),
    _control(C.NIST_CSF_2, "ID.RM-1", "Risk management processes are established", "Risk management processes are established and managed", "Risk Management Strategy"),
    _control(C.NIST_CSF_2, "PR.AC-1", "Identities and credentials are managed", "Identities and credentials are issued, managed, verified, and audited", "Access Control"),
    _control(C.NIST_CSF_2, "PR.AC-3", "Remote access is managed", "Remote access is managed with appropriate controls", "Access Control"),
    _control(C.NIST_CSF_2, "PR.AC-4", "Access permissions are managed", "Access permissions and authorizations are managed", "Access Control"),
    _control(C.NIST_CSF_2, "PR.AC-6", "Identities are proofed and bound to credentials", "Identities are proofed and bound to credentials for access", "Access Control"),
    _control(C.NIST_CSF_2, "PR.AC-7", "Users and devices are authenticated", "Users, devices, and other assets are authenticated", "Access Control"),
    _control(C.NIST_CSF_2, "PR.DS-1", "Data-at-rest is protected", "Data-at-rest is protected with encryption", "Data Security"),
    _control(C.NIST_CSF_2, "PR.DS-2", "Data-in-transit is protected", "Data-in-transit is protected with encryption", "Data Security"),
    _control(C.NIST_CSF_2, "PR.DS-3", "Assets are managed throughout removal", "Assets are formally managed throughout removal, transfers, and disposition", "Data Security"),
    _control(C.NIST_CSF_2, "PR.DS-5", "Protections against data leaks are implemented", "Protections against data leaks are implemented", "Data Security"),
    _control(C.NIST_CSF_2, "PR.IP-1", "Configuration management is established", "A baseline configuration of information technology is created and maintained", "Information Protection"),
    _control(C.NIST_CSF_2, "PR.IP-3", "Change management processes are established", "Configuration change control processes are established and enforced", "Information Protection"),
    _control(C.NIST_CSF_2, "PR.IP-4", "Backups are conducted and maintained", "Backups of information are conducted, maintained, and tested", "Information Protection"),
    _control(C.NIST_CSF_2, "PR.IP-8", "Security awareness training is provided", "All personnel are trained in security awareness", "Information Protection"),
    _control(C.NIST_CSF_2, "PR.MA-1", "Maintenance is performed", "Maintenance and repair of organizational assets is performed with controls", "Maintenance"),
    _control(C.NIST_CSF_2, "PR.PT-1", "Audit/log records are collected", "Audit/log records are determined, documented, and collected", "Protective Technology"),
    _control(C.NIST_CSF_2, "PR.PT-2", "Removable media is protected", "Removable media is protected and its use restricted", "Protective Technology"),
    _control(C.NIST_CSF_2, "PR.PT-3", "Access is limited", "The principle of least functionality is incorporated", "Protective Technology"),
    _control(C.NIST_CSF_2, "DE.AE-1", "Baseline of network operations is established", "A baseline of network operations and expected data flows is established", "Anomalies and Events"),
    _control(C.NIST_CSF_2, "DE.AE-2", "Events are analyzed", "Detected events are analyzed to understand attack targets and methods", "Anomalies and Events"),
    _control(C.NIST_CSF_2, "DE.AE-3", "Event data is correlated", "Event data is collected and correlated from multiple sources", "Anomalies and Events"),
    _control(C.NIST_CSF_2, "DE.CM-1", "Network is monitored", "The network is monitored to detect potential cybersecurity events", "Continuous Monitoring"),
    _control(C.NIST_CSF_2, "DE.CM-3", "Personnel activity is monitored", "Personnel activity is monitored to detect potential cybersecurity events", "Continuous Monitoring"),
    _control(C.NIST_CSF_2, "DE.CM-4", "Malicious code is detected", "Malicious code is detected through monitoring", "Continuous Monitoring"),
    _control(C.NIST_CSF_2, "DE.CM-7", "Monitoring for unauthorized connections", "Monitoring for unauthorized personnel, connections, devices, and software", "Continuous Monitoring"),
    _control(C.NIST_CSF_2, "RS.MA-1", "Incident response plan is executed", "Incident response plan is executed in response to an event", "Response"),
    _control(C.NIST_CSF_2, "RS.MA-2", "Incidents are reported", "Incidents are reported consistent with established criteria", "Response"),
    _control(C.NIST_CSF_2, "RS.CO-1", "Personnel know their roles", "Personnel know their roles and order of operations when a response is needed", "Response"),
    _control(C.NIST_CSF_2, "RS.CO-3", "Information is shared with stakeholders", "Information is shared with stakeholders consistent with response plans", "Response"),
    _control(C.NIST_CSF_2, "RC.RP-1", "Recovery plan is executed", "Recovery plan is executed during or after a cybersecurity event", "Recovery"),
    _control(C.NIST_CSF_2, "RC.IM-1", "Lessons learned are incorporated", "Lessons learned are incorporated into recovery plans", "Recovery"),
)

FRAMEWORK_DEFINITIONS[C.OWASP_TOP_10] = (
    _control(C.OWASP_TOP_10, "A01", "Broken Access Control", "Failures related to access control: unauthorized viewing or modification of data", "Access Control"),
    _control(C.OWASP_TOP_10, "A02", "Cryptographic Failures", "Failures related to cryptography: weak encryption, sensitive data exposure", "Cryptography"),
    _control(C.OWASP_TOP_10, "A03", "Injection", "Injection flaws: SQL, NoSQL, OS command injection", "Injection"),
    _control(C.OWASP_TOP_10, "A04", "Insecure Design", "Design flaws: missing threat modeling, insecure architecture", "Design"),
    _control(C.OWASP_TOP_10, "A05", "Security Misconfiguration", "Misconfigurations: default credentials, unpatched systems, open cloud storage", "Configuration"),
    _control(C.OWASP_TOP_10, "A06", "Vulnerable and Outdated Components", "Using components with known vulnerabilities", "Dependencies"),
    _control(C.OWASP_TOP_10, "A07", "Identification and Authentication Failures", "Authentication flaws: weak passwords, credential stuffing", "Authentication"),
    _control(C.OWASP_TOP_10, "A08", "Software and Data Integrity Failures", "Integrity failures: untrusted updates, CI/CD pipeline flaws", "Integrity"),
    _control(C.OWASP_TOP_10, "A09", "Security Logging and Monitoring Failures", "Insufficient logging, monitoring, and incident response", "Logging"),
    _control(C.OWASP_TOP_10, "A10", "Server-Side Request Forgery", "SSRF: server-side request forgery attacks", "Server Security"),
)

FRAMEWORK_DEFINITIONS[C.CWE] = (
    _control(C.CWE, "CWE-20", "Improper Input Validation", "Product does not validate or incorrectly validates input", "Input Validation"),
    _control(C.CWE, "CWE-22", "Improper Limitation of a Pathname to a Restricted Directory", "Path traversal vulnerability", "Path Traversal"),
    _control(C.CWE, "CWE-23", "Relative Path Traversal", "Relative path traversal vulnerability", "Path Traversal"),
    _control(C.CWE, "CWE-78", "Improper Neutralization of Special Elements used in an OS Command", "OS command injection", "Injection"),
    _control(C.CWE, "CWE-79", "Improper Neutralization of Input During Web Page Generation", "Cross-site scripting (XSS)", "XSS"),
    _control(C.CWE, "CWE-89", "Improper Neutralization of Special Elements used in an SQL Command", "SQL injection", "Injection"),
    _control(C.CWE, "CWE-94", "Improper Control of Generation of Code", "Code injection", "Injection"),
    _control(C.CWE, "CWE-102", "Struts: Duplicate Validation Forms", "Duplicate validation forms in Struts", "Configuration"),
    _control(C.CWE, "CWE-116", "Improper Encoding or Escaping of Output", "Improper encoding or escaping of output", "Encoding"),
    _control(C.CWE, "CWE-119", "Improper Restriction of Operations within Bounds", "Buffer overflow", "Memory Safety"),
    _control(C.CWE, "CWE-120", "Buffer Copy without Checking Size", "Classic buffer overflow", "Memory Safety"),
    _control(C.CWE, "CWE-125", "Out-of-bounds Read", "Reading past the end of a buffer", "Memory Safety"),
    _control(C.CWE, "CWE-190", "Integer Overflow or Wraparound", "Integer overflow or wraparound", "Arithmetic"),
    _control(C.CWE, "CWE-200", "Exposure of Sensitive Information", "Exposure of sensitive information to unauthorized actors", "Information Disclosure"),
    _control(C.CWE, "CWE-250", "Execution with Unnecessary Privileges", "Execution with unnecessary privileges", "Privilege Management"),
    _control(C.CWE, "CWE-255", "Credentials Management", "Credentials management errors", "Authentication"),
    _control(C.CWE, "CWE-256", "Unprotected Storage of Credentials", "Plaintext storage of passwords or credentials", "Cryptography"),
    _control(C.CWE, "CWE-259", "Use of Hard-coded Password", "Use of hard-coded password", "Authentication"),
    _control(C.CWE, "CWE-264", "Permissions, Privileges, and Access Controls", "Permissions, privileges, and access control issues", "Access Control"),
    _control(C.CWE, "CWE-269", "Improper Privilege Management", "Improper privilege management", "Access Control"),
    _control(C.CWE, "CWE-276", "Incorrect Default Permissions", "Incorrect default permissions", "Configuration"),
    _control(C.CWE, "CWE-284", "Improper Access Control", "Improper access control (generic)", "Access Control"),
    _control(C.CWE, "CWE-287", "Improper Authentication", "Improper authentication", "Authentication"),
    _control(C.CWE, "CWE-295", "Improper Certificate Validation", "Improper certificate validation", "Cryptography"),
    _control(C.CWE, "CWE-297", "Improper Validation of Host Certificate", "Improper validation of host certificate", "Cryptography"),
    _control(C.CWE, "CWE-306", "Missing Authentication for Critical Function", "Missing authentication for critical function", "Authentication"),
    _control(C.CWE, "CWE-307", "Improper Restriction of Authentication Attempts", "Improper restriction of brute-force attacks", "Authentication"),
    _control(C.CWE, "CWE-310", "Cryptographic Issues", "Cryptographic issues", "Cryptography"),
    _control(C.CWE, "CWE-311", "Missing Encryption of Sensitive Data", "Missing encryption of sensitive data", "Cryptography"),
    _control(C.CWE, "CWE-312", "Cleartext Storage of Sensitive Information", "Cleartext storage of sensitive information", "Cryptography"),
    _control(C.CWE, "CWE-319", "Cleartext Transmission of Sensitive Information", "Cleartext transmission of sensitive data", "Cryptography"),
    _control(C.CWE, "CWE-326", "Inadequate Encryption Strength", "Inadequate encryption strength", "Cryptography"),
    _control(C.CWE, "CWE-327", "Use of a Broken or Risky Cryptographic Algorithm", "Use of a broken or risky cryptographic algorithm", "Cryptography"),
    _control(C.CWE, "CWE-330", "Use of Insufficiently Random Values", "Use of insufficiently random values", "Cryptography"),
    _control(C.CWE, "CWE-345", "Insufficient Verification of Data Authenticity", "Insufficient verification of data authenticity", "Integrity"),
    _control(C.CWE, "CWE-346", "Origin Validation Error", "Origin validation error", "Access Control"),
    _control(C.CWE, "CWE-347", "Improper Verification of Cryptographic Signature", "Improper verification of cryptographic signature", "Cryptography"),
    _control(C.CWE, "CWE-352", "Cross-Site Request Forgery", "Cross-site request forgery (CSRF)", "Access Control"),
    _control(C.CWE, "CWE-362", "Race Condition", "Race condition", "Concurrency"),
    _control(C.CWE, "CWE-377", "Insecure Temporary File", "Insecure temporary file", "File Management"),
    _control(C.CWE, "CWE-379", "Creation of Temporary File in Directory with Insecure Permissions", "Creation of temporary file with insecure permissions", "File Management"),
    _control(C.CWE, "CWE-400", "Uncontrolled Resource Consumption", "Uncontrolled resource consumption", "Resource Management"),
    _control(C.CWE, "CWE-401", "Missing Release of Memory", "Missing release of memory after effective lifetime", "Memory Safety"),
    _control(C.CWE, "CWE-404", "Improper Resource Shutdown", "Improper resource shutdown or release", "Resource Management"),
    _control(C.CWE, "CWE-415", "Double Free", "Double free", "Memory Safety"),
    _control(C.CWE, "CWE-416", "Use After Free", "Use after free", "Memory Safety"),
    _control(C.CWE, "CWE-426", "Untrusted Search Path", "Untrusted search path", "Configuration"),
    _control(C.CWE, "CWE-434", "Unrestricted Upload of File with Dangerous Type", "Unrestricted file upload", "Input Validation"),
    _control(C.CWE, "CWE-444", "Inconsistent Interpretation of HTTP Requests", "HTTP request smuggling", "Injection"),
    _control(C.CWE, "CWE-451", "User Interface Misrepresentation", "User interface misrepresentation of critical information", "UI"),
    _control(C.CWE, "CWE-470", "Use of External-Controlled Input to Select Classes", "Use of externally-controlled input to select classes or code", "Injection"),
    _control(C.CWE, "CWE-476", "NULL Pointer Dereference", "NULL pointer dereference", "Memory Safety"),
    _control(C.CWE, "CWE-489", "Active Debug Code", "Active debug code", "Configuration"),
    _control(C.CWE, "CWE-494", "Download of Code Without Integrity Check", "Download of code without integrity check", "Integrity"),
    _control(C.CWE, "CWE-502", "Deserialization of Untrusted Data", "Deserialization of untrusted data", "Input Validation"),
    _control(C.CWE, "CWE-506", "Embedded Malicious Code", "Embedded malicious code", "Integrity"),
    _control(C.CWE, "CWE-521", "Weak Password Requirements", "Weak password requirements", "Authentication"),
    _control(C.CWE, "CWE-522", "Insufficiently Protected Credentials", "Insufficiently protected credentials", "Authentication"),
    _control(C.CWE, "CWE-523", "Unprotected Transport of Credentials", "Unprotected transport of credentials", "Cryptography"),
    _control(C.CWE, "CWE-532", "Insertion of Sensitive Information into Log File", "Insertion of sensitive information into log file", "Logging"),
    _control(C.CWE, "CWE-540", "Inclusion of Sensitive Information in Source Code", "Inclusion of sensitive information in source code", "Configuration"),
    _control(C.CWE, "CWE-548", "Exposure of Information Through Directory Listing", "Directory listing exposure", "Configuration"),
    _control(C.CWE, "CWE-601", "URL Redirection to Untrusted Site", "Open redirect", "Input Validation"),
    _control(C.CWE, "CWE-602", "Client-Side Enforcement of Server-Side Security", "Client-side enforcement of server-side security", "Access Control"),
    _control(C.CWE, "CWE-611", "Improper Restriction of XML External Entity Reference", "XXE injection", "Injection"),
    _control(C.CWE, "CWE-613", "Insufficient Session Expiration", "Insufficient session expiration", "Authentication"),
    _control(C.CWE, "CWE-614", "Sensitive Cookie in HTTPS Session Without Secure Attribute", "Sensitive cookie in HTTPS session without secure attribute", "Cryptography"),
    _control(C.CWE, "CWE-620", "Unverified Password Change", "Unverified password change", "Authentication"),
    _control(C.CWE, "CWE-639", "Authorization Bypass Through User-Controlled Key", "Insecure direct object reference (IDOR)", "Access Control"),
    _control(C.CWE, "CWE-640", "Weak Password Recovery Mechanism", "Weak password recovery mechanism", "Authentication"),
    _control(C.CWE, "CWE-643", "Improper Neutralization of Data within XPath Expressions", "XPath injection", "Injection"),
    _control(C.CWE, "CWE-645", "Insufficiently Secured Authentication Methods", "Insufficiently secured authentication methods", "Authentication"),
    _control(C.CWE, "CWE-649", "Reliance on Obfuscation", "Reliance on obfuscation or concealment for security", "Design"),
    _control(C.CWE, "CWE-650", "Trust of HTTP Permission Methods", "Trust of HTTP permission methods", "Access Control"),
    _control(C.CWE, "CWE-652", "Improper Neutralization of Data Within XQuery Expressions", "XQuery injection", "Injection"),
    _control(C.CWE, "CWE-657", "Violation of Secure Design Principles", "Violation of secure design principles", "Design"),
    _control(C.CWE, "CWE-664", "Improper Control of a Resource Through its Lifetime", "Improper control of a resource through its lifetime", "Resource Management"),
    _control(C.CWE, "CWE-665", "Improper Initialization", "Improper initialization", "Memory Safety"),
    _control(C.CWE, "CWE-667", "Improper Locking", "Improper locking", "Concurrency"),
    _control(C.CWE, "CWE-668", "Exposure of Resource to Wrong Sphere", "Exposure of resource to wrong sphere", "Access Control"),
    _control(C.CWE, "CWE-670", "Always-Incorrect Control Flow Implementation", "Always-incorrect control flow implementation", "Logic"),
    _control(C.CWE, "CWE-672", "Operation on a Resource After Expiration", "Operation on a resource after expiration or release", "Resource Management"),
    _control(C.CWE, "CWE-674", "Uncontrolled Recursion", "Uncontrolled recursion", "Resource Management"),
    _control(C.CWE, "CWE-676", "Use of Potentially Dangerous Function", "Use of potentially dangerous function", "Memory Safety"),
    _control(C.CWE, "CWE-680", "Integer Overflow to Buffer Overflow", "Integer overflow to buffer overflow", "Memory Safety"),
    _control(C.CWE, "CWE-681", "Incorrect Conversion between Numeric Types", "Incorrect conversion between numeric types", "Arithmetic"),
    _control(C.CWE, "CWE-682", "Incorrect Calculation", "Incorrect calculation", "Arithmetic"),
    _control(C.CWE, "CWE-684", "Incorrect Provision of Specification", "Incorrect provision of specification or mechanism", "Design"),
    _control(C.CWE, "CWE-691", "Insufficient Control Flow Management", "Insufficient control flow management", "Logic"),
    _control(C.CWE, "CWE-693", "Protection Mechanism Failure", "Protection mechanism failure", "Design"),
    _control(C.CWE, "CWE-694", "Use of Multiple Resources with Duplicate Identifier", "Use of multiple resources with duplicate identifier", "Resource Management"),
    _control(C.CWE, "CWE-697", "Incorrect Comparison", "Incorrect comparison", "Logic"),
    _control(C.CWE, "CWE-703", "Improper Check for Unusual Conditions", "Improper check for unusual or exceptional conditions", "Error Handling"),
    _control(C.CWE, "CWE-704", "Incorrect Type Conversion or Cast", "Incorrect type conversion or cast", "Type Safety"),
    _control(C.CWE, "CWE-706", "Use of Incorrectly-Resolved Name or Reference", "Use of incorrectly-resolved name or reference", "Configuration"),
    _control(C.CWE, "CWE-707", "Improper Neutralization", "Improper neutralization of special elements", "Injection"),
    _control(C.CWE, "CWE-710", "Improper Adherence to Coding Standards", "Improper adherence to coding standards", "Quality"),
    _control(C.CWE, "CWE-732", "Incorrect Permission Assignment for Critical Resource", "Incorrect permission assignment for critical resource", "Access Control"),
    _control(C.CWE, "CWE-749", "Exposed Dangerous Method or Function", "Exposed dangerous method or function", "Access Control"),
    _control(C.CWE, "CWE-754", "Improper Check for Unusual Conditions", "Improper check for unusual or exceptional conditions", "Error Handling"),
    _control(C.CWE, "CWE-755", "Improper Handling of Exceptional Conditions", "Improper handling of exceptional conditions", "Error Handling"),
    _control(C.CWE, "CWE-759", "Use of a One-Way Hash without a Salt", "Use of a one-way hash without a salt", "Cryptography"),
    _control(C.CWE, "CWE-760", "Use of a One-Way Hash with a Predictable Salt", "Use of a one-way hash with a predictable salt", "Cryptography"),
    _control(C.CWE, "CWE-761", "Freeing of Memory Not on the Heap", "Freeing of memory not on the heap", "Memory Safety"),
    _control(C.CWE, "CWE-762", "Mismatched Memory Management Routines", "Mismatched memory management routines", "Memory Safety"),
    _control(C.CWE, "CWE-763", "Release of Invalid Pointer", "Release of invalid pointer", "Memory Safety"),
    _control(C.CWE, "CWE-765", "Multiple Unlocks", "Multiple unlocks", "Concurrency"),
    _control(C.CWE, "CWE-767", "Access to Critical Private Variable via Public Method", "Access to critical private variable via public method", "Access Control"),
    _control(C.CWE, "CWE-768", "Incorrect Short Circuit Evaluation", "Incorrect short circuit evaluation", "Logic"),
    _control(C.CWE, "CWE-770", "Allocation of Resources Without Limits", "Allocation of resources without limits or throttling", "Resource Management"),
    _control(C.CWE, "CWE-772", "Missing Release of Resource", "Missing release of resource after effective lifetime", "Resource Management"),
    _control(C.CWE, "CWE-775", "Missing Release of File Descriptor", "Missing release of file descriptor after effective lifetime", "Resource Management"),
    _control(C.CWE, "CWE-776", "Improper Restriction of Recursive Entity References", "Improper restriction of recursive entity references in DTDs", "Injection"),
    _control(C.CWE, "CWE-777", "Regular Expression Without Anchors", "Regular expression without anchors", "Input Validation"),
    _control(C.CWE, "CWE-779", "Logging of Excessive Data", "Logging of excessive data", "Logging"),
    _control(C.CWE, "CWE-782", "Exposed IOCTL with Insufficient Access Control", "Exposed IOCTL with insufficient access control", "Access Control"),
    _control(C.CWE, "CWE-784", "Reliance on Cookies without Validation", "Reliance on cookies without validation", "Authentication"),
    _control(C.CWE, "CWE-787", "Out-of-bounds Write", "Out-of-bounds write", "Memory Safety"),
    _control(C.CWE, "CWE-789", "Uncontrolled Memory Allocation", "Uncontrolled memory allocation", "Resource Management"),
    _control(C.CWE, "CWE-798", "Use of Hard-coded Credentials", "Use of hard-coded credentials", "Authentication"),
    _control(C.CWE, "CWE-799", "Improper Control of Interaction Frequency", "Improper control of interaction frequency", "Access Control"),
    _control(C.CWE, "CWE-807", "Reliance on Untrusted Inputs", "Reliance on untrusted inputs in a security decision", "Input Validation"),
    _control(C.CWE, "CWE-825", "Expired Pointer Dereference", "Expired pointer dereference", "Memory Safety"),
    _control(C.CWE, "CWE-829", "Inclusion of Functionality from Untrusted Control Sphere", "Inclusion of functionality from untrusted control sphere", "Integrity"),
    _control(C.CWE, "CWE-830", "Inclusion of Web Functionality from an Untrusted Source", "Inclusion of web functionality from an untrusted source", "Integrity"),
    _control(C.CWE, "CWE-835", "Loop with Unreachable Exit Condition", "Loop with unreachable exit condition", "Logic"),
    _control(C.CWE, "CWE-837", "Improper Enforcement of a Single, Unique Action", "Improper enforcement of a single, unique action", "Access Control"),
    _control(C.CWE, "CWE-838", "Inappropriate Encoding for Output Context", "Inappropriate encoding for output context", "Encoding"),
    _control(C.CWE, "CWE-841", "Improper Enforcement of Behavioral Workflow", "Improper enforcement of behavioral workflow", "Access Control"),
    _control(C.CWE, "CWE-842", "Placement of User into Incorrect Group", "Placement of user into incorrect group", "Access Control"),
    _control(C.CWE, "CWE-843", "Access of Resource Using Incompatible Type", "Access of resource using incompatible type", "Type Safety"),
    _control(C.CWE, "CWE-862", "Missing Authorization", "Missing authorization", "Access Control"),
    _control(C.CWE, "CWE-863", "Incorrect Authorization", "Incorrect authorization", "Access Control"),
    _control(C.CWE, "CWE-867", "Weak Authentication in Communication Protocol", "Weak authentication in communication protocol", "Authentication"),
    _control(C.CWE, "CWE-909", "Missing Initialization of Resource", "Missing initialization of resource", "Resource Management"),
    _control(C.CWE, "CWE-912", "Hidden Functionality", "Hidden functionality (backdoor)", "Integrity"),
    _control(C.CWE, "CWE-913", "Improper Control of Dynamically-Managed Code", "Improper control of dynamically-managed code resources", "Integrity"),
    _control(C.CWE, "CWE-915", "Improperly Controlled Modification of Dynamically-Determined Object", "Improperly controlled modification of dynamically-determined object", "Injection"),
    _control(C.CWE, "CWE-916", "Use of Password Hash With Insufficient Computational Effort", "Use of password hash with insufficient computational effort", "Cryptography"),
    _control(C.CWE, "CWE-918", "Server-Side Request Forgery (SSRF)", "Server-side request forgery", "Injection"),
    _control(C.CWE, "CWE-921", "Storage of Sensitive Data in a Mechanism without Access Control", "Storage of sensitive data without access control", "Access Control"),
    _control(C.CWE, "CWE-922", "Insecure Storage of Sensitive Information", "Insecure storage of sensitive information", "Cryptography"),
    _control(C.CWE, "CWE-923", "Improper Restriction of Communication Channel", "Improper restriction of communication channel", "Access Control"),
    _control(C.CWE, "CWE-924", "Improper Enforcement of Message Integrity", "Improper enforcement of message integrity", "Integrity"),
    _control(C.CWE, "CWE-925", "Improper Verification of Intent by Actor", "Improper verification of intent by actor", "Access Control"),
    _control(C.CWE, "CWE-926", "Improper Export of Android Application Components", "Improper export of Android application components", "Configuration"),
    _control(C.CWE, "CWE-927", "Use of Implicit Intent for Sensitive Communication", "Use of implicit intent for sensitive communication", "Access Control"),
    _control(C.CWE, "CWE-939", "Improper Authorization in Handler", "Improper authorization in handler", "Access Control"),
    _control(C.CWE, "CWE-940", "Improper Verification of Source of a Communication Channel", "Improper verification of source of a communication channel", "Authentication"),
    _control(C.CWE, "CWE-941", "Composite: User-Controlled Bypass", "Composite: user-controlled bypass of access controls", "Access Control"),
    _control(C.CWE, "CWE-942", "Permissive Cross-domain Policy with Untrusted Domains", "Permissive cross-domain policy with untrusted domains", "Configuration"),
    _control(C.CWE, "CWE-943", "Improper Neutralization of Special Elements in Data Query Logic", "Improper neutralization of special elements in data query logic", "Injection"),
)

FRAMEWORK_DEFINITIONS[C.CVE] = (
    _control(C.CVE, "CVE-2025-1234", "Known vulnerability detection", "Match against known CVE entries for discovered software versions", "Vulnerability Management"),
    _control(C.CVE, "CVE-2025-5678", "Critical remote code execution", "Detect critical RCE vulnerabilities in discovered services", "Vulnerability Management"),
    _control(C.CVE, "CVE-2025-9012", "Privilege escalation vulnerability", "Detect privilege escalation CVEs in discovered components", "Vulnerability Management"),
    _control(C.CVE, "CVE-2025-3456", "Information disclosure vulnerability", "Detect information disclosure CVEs", "Vulnerability Management"),
    _control(C.CVE, "CVE-2025-7890", "Denial of service vulnerability", "Detect DoS CVEs in discovered services", "Vulnerability Management"),
    _control(C.CVE, "CVE-2025-2345", "Cross-site scripting (XSS)", "Detect XSS CVEs in web applications", "Vulnerability Management"),
    _control(C.CVE, "CVE-2025-6789", "SQL injection vulnerability", "Detect SQL injection CVEs", "Vulnerability Management"),
    _control(C.CVE, "CVE-2025-4321", "Authentication bypass vulnerability", "Detect authentication bypass CVEs", "Vulnerability Management"),
)

FRAMEWORK_DEFINITIONS[C.MITRE_ATT_CK] = (
    _control(C.MITRE_ATT_CK, "T1078", "Valid Accounts", "Adversary may obtain and abuse credentials of existing accounts", "Initial Access"),
    _control(C.MITRE_ATT_CK, "T1190", "Exploit Public-Facing Application", "Adversary may exploit a vulnerability in a public-facing application", "Initial Access"),
    _control(C.MITRE_ATT_CK, "T1133", "External Remote Services", "Adversary may use external remote services for initial access", "Initial Access"),
    _control(C.MITRE_ATT_CK, "T1566", "Phishing", "Adversary may send phishing messages to gain access", "Initial Access"),
    _control(C.MITRE_ATT_CK, "T1189", "Drive-by Compromise", "Adversary may gain access through a user visiting a compromised site", "Initial Access"),
    _control(C.MITRE_ATT_CK, "T1059", "Command and Scripting Interpreter", "Adversary may abuse command and script interpreters", "Execution"),
    _control(C.MITRE_ATT_CK, "T1204", "User Execution", "Adversary relies on user execution for initial access", "Execution"),
    _control(C.MITRE_ATT_CK, "T1053", "Scheduled Task/Job", "Adversary may use scheduled tasks for execution", "Execution"),
    _control(C.MITRE_ATT_CK, "T1098", "Account Manipulation", "Adversary may manipulate accounts for persistence", "Persistence"),
    _control(C.MITRE_ATT_CK, "T1136", "Create Account", "Adversary may create an account for persistence", "Persistence"),
    _control(C.MITRE_ATT_CK, "T1505", "Server Software Component", "Adversary may install server software components for persistence", "Persistence"),
    _control(C.MITRE_ATT_CK, "T1078_002", "Domain Accounts", "Adversary may use domain accounts for privilege escalation", "Privilege Escalation"),
    _control(C.MITRE_ATT_CK, "T1055", "Process Injection", "Adversary may inject code into processes for privilege escalation", "Privilege Escalation"),
    _control(C.MITRE_ATT_CK, "T1068", "Exploitation for Privilege Escalation", "Adversary may exploit a vulnerability for privilege escalation", "Privilege Escalation"),
    _control(C.MITRE_ATT_CK, "T1003", "OS Credential Dumping", "Adversary may dump credentials from systems", "Credential Access"),
    _control(C.MITRE_ATT_CK, "T1552", "Unsecured Credentials", "Adversary may search for unsecured credentials", "Credential Access"),
    _control(C.MITRE_ATT_CK, "T1555", "Credentials from Password Stores", "Adversary may extract credentials from password stores", "Credential Access"),
    _control(C.MITRE_ATT_CK, "T1083", "File and Directory Discovery", "Adversary may enumerate files and directories", "Discovery"),
    _control(C.MITRE_ATT_CK, "T1046", "Network Service Discovery", "Adversary may scan for network services", "Discovery"),
    _control(C.MITRE_ATT_CK, "T1069", "Permission Groups Discovery", "Adversary may discover permission groups", "Discovery"),
    _control(C.MITRE_ATT_CK, "T1482", "Domain Trust Discovery", "Adversary may discover domain trust relationships", "Discovery"),
    _control(C.MITRE_ATT_CK, "T1071", "Application Layer Protocol", "Adversary may use application layer protocols for C2", "Command and Control"),
    _control(C.MITRE_ATT_CK, "T1573", "Encrypted Channel", "Adversary may use encrypted channels for C2", "Command and Control"),
    _control(C.MITRE_ATT_CK, "T1095", "Non-Application Layer Protocol", "Adversary may use non-application layer protocols for C2", "Command and Control"),
    _control(C.MITRE_ATT_CK, "T1041", "Exfiltration Over C2 Channel", "Adversary may exfiltrate data over the C2 channel", "Exfiltration"),
    _control(C.MITRE_ATT_CK, "T1567", "Exfiltration Over Web Service", "Adversary may exfiltrate data over web services", "Exfiltration"),
    _control(C.MITRE_ATT_CK, "T1048", "Exfiltration Over Alternative Protocol", "Adversary may exfiltrate data over alternative protocols", "Exfiltration"),
    _control(C.MITRE_ATT_CK, "T1485", "Data Destruction", "Adversary may destroy data", "Impact"),
    _control(C.MITRE_ATT_CK, "T1496", "Resource Hijacking", "Adversary may hijack resources for malicious purposes", "Impact"),
    _control(C.MITRE_ATT_CK, "T1490", "Inhibit System Recovery", "Adversary may inhibit system recovery", "Impact"),
    _control(C.MITRE_ATT_CK, "T1529", "System Shutdown/Reboot", "Adversary may shutdown or reboot systems", "Impact"),
)

FRAMEWORK_DEFINITIONS[C.ISO_27001] = (
    _control(C.ISO_27001, "A.5.1", "Information security policy", "Management direction for information security", "Information Security Policies"),
    _control(C.ISO_27001, "A.5.9", "Inventory of information and other associated assets", "Inventory of information and other associated assets", "Asset Management"),
    _control(C.ISO_27001, "A.5.10", "Acceptable use of information", "Acceptable use of information and other associated assets", "Asset Management"),
    _control(C.ISO_27001, "A.5.11", "Return of assets", "Return of assets upon termination of employment or agreement", "Asset Management"),
    _control(C.ISO_27001, "A.5.15", "Access control", "Access control policy and procedures", "Access Control"),
    _control(C.ISO_27001, "A.5.16", "Identity management", "Identity management for personnel and third parties", "Access Control"),
    _control(C.ISO_27001, "A.5.17", "Authentication information", "Authentication information management", "Access Control"),
    _control(C.ISO_27001, "A.5.18", "Access rights", "Access rights management and review", "Access Control"),
    _control(C.ISO_27001, "A.5.24", "Information security incident management", "Information security incident management planning and preparation", "Incident Management"),
    _control(C.ISO_27001, "A.5.25", "Assessment of information security events", "Assessment and decision on information security events", "Incident Management"),
    _control(C.ISO_27001, "A.5.26", "Response to information security incidents", "Response to information security incidents", "Incident Management"),
    _control(C.ISO_27001, "A.5.29", "Information security during disruption", "Information security during business disruption", "Business Continuity"),
    _control(C.ISO_27001, "A.5.30", "ICT readiness for business continuity", "ICT readiness for business continuity", "Business Continuity"),
    _control(C.ISO_27001, "A.5.31", "Legal and regulatory requirements", "Identification of legal, statutory, regulatory and contractual requirements", "Compliance"),
    _control(C.ISO_27001, "A.5.33", "Protection of records", "Protection of records against loss, destruction, and falsification", "Compliance"),
    _control(C.ISO_27001, "A.5.36", "Compliance with policies", "Compliance with information security policies and standards", "Compliance"),
    _control(C.ISO_27001, "A.5.37", "Documented operating procedures", "Documented operating procedures for information processing", "Operations Security"),
    _control(C.ISO_27001, "A.6.1", "Background verification checks", "Background verification checks for personnel", "Human Resources"),
    _control(C.ISO_27001, "A.6.3", "Information security awareness", "Information security awareness, education, and training", "Human Resources"),
    _control(C.ISO_27001, "A.7.1", "Physical security perimeter", "Physical security perimeters and entry controls", "Physical Security"),
    _control(C.ISO_27001, "A.7.4", "Physical device security", "Physical device security and clear desk policy", "Physical Security"),
    _control(C.ISO_27001, "A.7.7", "Secure disposal", "Secure disposal or reuse of equipment", "Physical Security"),
    _control(C.ISO_27001, "A.7.8", "Unattended user equipment", "Clear screen and lock session for unattended user equipment", "Physical Security"),
    _control(C.ISO_27001, "A.8.1", "User endpoint devices", "Security of user endpoint devices", "Endpoint Security"),
    _control(C.ISO_27001, "A.8.2", "Privileged access rights", "Management of privileged access rights", "Access Control"),
    _control(C.ISO_27001, "A.8.3", "Information access restriction", "Restriction of information access", "Access Control"),
    _control(C.ISO_27001, "A.8.4", "Access to source code", "Access to source code protection", "Application Security"),
    _control(C.ISO_27001, "A.8.5", "Secure authentication", "Secure authentication methods", "Access Control"),
    _control(C.ISO_27001, "A.8.6", "Capacity management", "Capacity management of resources", "Operations Security"),
    _control(C.ISO_27001, "A.8.7", "Protection against malware", "Protection against malware", "Endpoint Security"),
    _control(C.ISO_27001, "A.8.8", "Management of technical vulnerabilities", "Management of technical vulnerabilities", "Vulnerability Management"),
    _control(C.ISO_27001, "A.8.9", "Configuration management", "Configuration management of systems and applications", "Operations Security"),
    _control(C.ISO_27001, "A.8.10", "Information deletion", "Information deletion from systems and storage", "Asset Management"),
    _control(C.ISO_27001, "A.8.11", "Data masking", "Data masking controls", "Cryptography"),
    _control(C.ISO_27001, "A.8.12", "Data leakage prevention", "Data leakage prevention controls", "Data Protection"),
    _control(C.ISO_27001, "A.8.13", "Backup of information", "Backup of information, software, and system images", "Business Continuity"),
    _control(C.ISO_27001, "A.8.14", "Redundancy", "Redundancy of information processing facilities", "Business Continuity"),
    _control(C.ISO_27001, "A.8.15", "Logging", "Event logging and monitoring", "Operations Security"),
    _control(C.ISO_27001, "A.8.16", "Clock synchronization", "Clock synchronization of logging systems", "Operations Security"),
    _control(C.ISO_27001, "A.8.17", "Protection of log information", "Protection of log information against tampering", "Operations Security"),
    _control(C.ISO_27001, "A.8.18", "Administrator and operator logs", "Administrator and operator activity logs", "Operations Security"),
    _control(C.ISO_27001, "A.8.19", "Installation of software", "Installation of software on operational systems", "Operations Security"),
    _control(C.ISO_27001, "A.8.20", "Network security", "Network security controls and segregation", "Network Security"),
    _control(C.ISO_27001, "A.8.21", "Segregation in networks", "Segregation of networks based on trust", "Network Security"),
    _control(C.ISO_27001, "A.8.22", "Network services", "Security of network services", "Network Security"),
    _control(C.ISO_27001, "A.8.23", "Web filtering", "Web filtering and access controls", "Network Security"),
    _control(C.ISO_27001, "A.8.24", "Use of cryptography", "Use of cryptography for data protection", "Cryptography"),
    _control(C.ISO_27001, "A.8.25", "Secure development lifecycle", "Secure development lifecycle and change management", "Application Security"),
    _control(C.ISO_27001, "A.8.26", "Application security requirements", "Application security requirements definition", "Application Security"),
    _control(C.ISO_27001, "A.8.27", "Secure system architecture", "Secure system architecture and design principles", "Application Security"),
    _control(C.ISO_27001, "A.8.28", "Secure coding", "Secure coding practices", "Application Security"),
    _control(C.ISO_27001, "A.8.29", "Vulnerability testing", "Vulnerability testing in development and acceptance", "Application Security"),
    _control(C.ISO_27001, "A.8.30", "Outsourced development", "Outsourced development security requirements", "Application Security"),
    _control(C.ISO_27001, "A.8.31", "Separation of environments", "Separation of development, test, and production environments", "Application Security"),
    _control(C.ISO_27001, "A.8.33", "Test information protection", "Protection of test data", "Application Security"),
    _control(C.ISO_27001, "A.8.34", "Audit logging for suppliers", "Audit logging for supplier access", "Supplier Relationships"),
    _control(C.ISO_27001, "A.8.35", "Change management", "Change management for information processing", "Operations Security"),
)

FRAMEWORK_DEFINITIONS[C.PCI_DSS_4] = (
    _control(C.PCI_DSS_4, "1.1", "Install and maintain network security controls", "Install and maintain network security controls to protect cardholder data", "Network Security"),
    _control(C.PCI_DSS_4, "1.2", "Network security controls configuration", "Configure network security controls to deny all traffic by default", "Network Security"),
    _control(C.PCI_DSS_4, "1.4", "Network connections between trusted and untrusted networks", "Control network connections between trusted and untrusted networks", "Network Security"),
    _control(C.PCI_DSS_4, "1.5", "Risk assessment for network changes", "Risk assessment for network security control changes", "Network Security"),
    _control(C.PCI_DSS_4, "2.1", "Configuration standards", "Apply configuration standards to all system components", "Configuration"),
    _control(C.PCI_DSS_4, "2.2", "Default credentials", "Change vendor defaults and remove unnecessary services", "Configuration"),
    _control(C.PCI_DSS_4, "2.3", "Wireless environment security", "Secure wireless environments with strong encryption", "Configuration"),
    _control(C.PCI_DSS_4, "3.1", "Protect stored cardholder data", "Protect stored cardholder data through encryption and truncation", "Data Protection"),
    _control(C.PCI_DSS_4, "3.2", "Cardholder data storage", "Define and limit cardholder data storage", "Data Protection"),
    _control(C.PCI_DSS_4, "3.3", "Sensitive authentication data", "Do not store sensitive authentication data after authorization", "Data Protection"),
    _control(C.PCI_DSS_4, "3.4", "PAN display masking", "Mask PAN when displayed", "Data Protection"),
    _control(C.PCI_DSS_4, "3.5", "Encryption keys management", "Secure management of encryption keys", "Cryptography"),
    _control(C.PCI_DSS_4, "3.6", "Cryptographic documentation", "Document and implement cryptographic procedures", "Cryptography"),
    _control(C.PCI_DSS_4, "4.1", "Cardholder data encryption in transit", "Encrypt cardholder data in transit over public networks", "Data Protection"),
    _control(C.PCI_DSS_4, "4.2", "TLS and certificate management", "Use strong TLS and proper certificate validation", "Data Protection"),
    _control(C.PCI_DSS_4, "5.1", "Anti-malware protection", "Deploy and maintain anti-malware on all systems", "Malware Protection"),
    _control(C.PCI_DSS_4, "5.2", "Anti-malware updates", "Keep anti-malware mechanisms updated", "Malware Protection"),
    _control(C.PCI_DSS_4, "5.3", "Anti-malware scanning", "Perform regular anti-malware scans", "Malware Protection"),
    _control(C.PCI_DSS_4, "6.1", "Vulnerability management process", "Establish and maintain a vulnerability management process", "Vulnerability Management"),
    _control(C.PCI_DSS_4, "6.2", "Critical security patches", "Apply critical security patches in a timely manner", "Vulnerability Management"),
    _control(C.PCI_DSS_4, "6.3", "Penetration testing", "Perform penetration testing on network and applications", "Vulnerability Management"),
    _control(C.PCI_DSS_4, "6.4", "Internal and external vulnerability scans", "Perform regular internal and external vulnerability scans", "Vulnerability Management"),
    _control(C.PCI_DSS_4, "7.1", "Access control for cardholder data", "Restrict access to cardholder data by business need-to-know", "Access Control"),
    _control(C.PCI_DSS_4, "7.2", "Access control system", "Establish an access control system for systems and data", "Access Control"),
    _control(C.PCI_DSS_4, "7.3", "Access review", "Review access rights at least quarterly", "Access Control"),
    _control(C.PCI_DSS_4, "8.1", "Identity and authentication", "Identify and authenticate users accessing system components", "Authentication"),
    _control(C.PCI_DSS_4, "8.2", "Strong authentication", "Use strong authentication with MFA for administrative access", "Authentication"),
    _control(C.PCI_DSS_4, "8.3", "Password security", "Implement password strength and management", "Authentication"),
    _control(C.PCI_DSS_4, "8.4", "MFA implementation", "Implement multi-factor authentication for all remote access", "Authentication"),
    _control(C.PCI_DSS_4, "9.1", "Physical access controls", "Restrict physical access to cardholder data", "Physical Security"),
    _control(C.PCI_DSS_4, "9.2", "Visitor management", "Manage visitors and physical access", "Physical Security"),
    _control(C.PCI_DSS_4, "9.3", "Media security", "Securely store and destroy media containing cardholder data", "Physical Security"),
    _control(C.PCI_DSS_4, "10.1", "Logging mechanisms", "Log all access to systems and cardholder data", "Logging"),
    _control(C.PCI_DSS_4, "10.2", "Automated logging", "Implement automated audit trails for all system components", "Logging"),
    _control(C.PCI_DSS_4, "10.3", "Log retention", "Retain audit logs for at least 12 months", "Logging"),
    _control(C.PCI_DSS_4, "10.4", "Log protection", "Protect audit logs from modification and deletion", "Logging"),
    _control(C.PCI_DSS_4, "10.6", "Daily log review", "Review security events and logs at least daily", "Logging"),
    _control(C.PCI_DSS_4, "11.1", "Wireless access point detection", "Detect and monitor wireless access points", "Monitoring"),
    _control(C.PCI_DSS_4, "11.2", "File integrity monitoring", "Use file integrity monitoring to detect changes", "Monitoring"),
    _control(C.PCI_DSS_4, "11.3", "Network and application penetration testing", "Perform penetration testing at least annually", "Monitoring"),
    _control(C.PCI_DSS_4, "11.4", "Intrusion detection and prevention", "Deploy intrusion detection and prevention systems", "Monitoring"),
    _control(C.PCI_DSS_4, "11.5", "Change detection", "Deploy change detection mechanisms on critical systems", "Monitoring"),
    _control(C.PCI_DSS_4, "12.1", "Information security policy", "Establish and maintain an information security policy", "Policy"),
    _control(C.PCI_DSS_4, "12.2", "Risk assessment", "Perform periodic risk assessments", "Policy"),
    _control(C.PCI_DSS_4, "12.3", "Security awareness program", "Establish a security awareness program for personnel", "Policy"),
    _control(C.PCI_DSS_4, "12.4", "Incident response plan", "Establish and implement an incident response plan", "Policy"),
    _control(C.PCI_DSS_4, "12.5", "Security testing", "Ensure security testing is conducted at least annually", "Policy"),
    _control(C.PCI_DSS_4, "12.6", "Service provider oversight", "Manage and monitor service provider security", "Policy"),
    _control(C.PCI_DSS_4, "12.9", "Third party security", "Ensure third parties handling cardholder data meet security requirements", "Policy"),
)
